FROM node:latest

WORKDIR /app

COPY package*.json ./

ARG MYSQL_HOST=localhost
ARG MYSQL_PORT=3306
ARG MYSQL_USER=root
ARG MYSQL_PASSWORD=root
ARG MYSQL_DBNAME=code-food-db

ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_PORT=$MYSQL_PORT
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_DBNAME=$MYSQL_DBNAME

COPY . .
RUN cp .env.example .env

EXPOSE 3030

CMD npm run start-prod